<h2>Sign up using this form</h2>

<?php echo $this->tag->form("signup/register"); ?>

<p>
    <label for="username">username</label>
    <?php echo $this->tag->textField("username"); ?>
</p>

<p>
    <label for="email">E-Mail</label>
    <?php echo $this->tag->emailField("email"); ?>
</p>

<p>
    <label for="password">password</label>
    <?php echo $this->tag->passwordField("password"); ?>
</p>

<p>
    <?php echo $this->tag->submitButton("Register"); ?>
</p>

</form>